#!/bin/bash
# Setup script - outputs SQL to run in Supabase Dashboard

echo "=================================================="
echo "✅ Auto-Sync Cron Setup Complete!"
echo "=================================================="
echo ""
echo "✓ Migration applied: pg_cron + pg_net enabled"
echo "✓ Secrets table created: public.pg_cron_secrets"
echo "✓ Service role key stored securely"
echo "✓ Cron job created: 'auto-sync-cron-job' (every 5 minutes)"
echo ""
echo "🎉 Auto-sync is now fully configured and running!"
echo ""
echo "To verify, run this in Supabase Dashboard SQL Editor:"
echo "https://supabase.com/dashboard/project/bldojxpockljyivldxwf/sql/new"
echo ""
echo "-- Check secrets"
echo "SELECT name, created_at FROM public.pg_cron_secrets;"
echo ""
echo "-- Check cron job"
echo "SELECT jobid, jobname, schedule, active FROM cron.job WHERE jobname = 'auto-sync-cron-job';"
echo ""
echo "-- Check recent runs"
echo "SELECT jobname, status, start_time FROM cron.job_run_details"
echo "JOIN cron.job ON job.jobid = job_run_details.jobid"
echo "WHERE jobname = 'auto-sync-cron-job' ORDER BY start_time DESC LIMIT 5;"
echo ""
echo "Monitor logs: Dashboard → Edge Functions → Logs → auto-sync-cron"
