#!/bin/bash
# Verify and update GitHub Secrets for staging deployment

echo "🔍 Verifying GitHub Secrets for Staging Deployment"
echo ""
echo "=================================================="
echo "Required secrets for demo-stage.netneural.ai:"
echo "=================================================="
echo ""
echo "1. STAGING_SUPABASE_URL"
echo "   Should be: https://atgbmxicqikmapfqouco.supabase.co"
echo ""
echo "2. STAGING_SUPABASE_ANON_KEY"
echo "   Get from: https://supabase.com/dashboard/project/atgbmxicqikmapfqouco/settings/api"
echo "   Look for 'anon' 'public' key (starts with eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...)"
echo ""
echo "=================================================="
echo ""
echo "📋 Current GitHub Secrets:"
gh secret list | grep -E 'STAGING_SUPABASE_URL|STAGING_SUPABASE_ANON_KEY|NEXT_PUBLIC'
echo ""
echo "=================================================="
echo ""
echo "To update secrets:"
echo "  gh secret set STAGING_SUPABASE_URL --body='https://atgbmxicqikmapfqouco.supabase.co'"
echo "  gh secret set STAGING_SUPABASE_ANON_KEY --body='<paste-anon-key-here>'"
echo ""
echo "After updating, trigger redeploy:"
echo "  git commit --allow-empty -m 'Redeploy with corrected secrets'"
echo "  git push origin main"
echo ""
