#!/bin/bash

# NetNeural Development Environment Setup with Remote Docker
# This script sets up the complete environment using SSH Docker tunnel to remote server

set -e

echo "🚀 Setting up NetNeural Development Environment (Remote Docker Mode)"
echo "=================================================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_step() {
    echo -e "${BLUE}📋 $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check if we're in the development directory
if [ ! -f "package.json" ] || [ ! -d "apps" ]; then
    print_error "Please run this script from the development directory"
    exit 1
fi

# Check for remote Docker configuration
print_step "Checking remote Docker configuration..."
if [ -z "$DOCKER_HOST" ]; then
    print_warning "DOCKER_HOST not set. Setting up SSH tunnel to remote Docker..."
    
    # Check if SSH tunnel script exists
    if [ -f "scripts/connect-docker.sh" ]; then
        print_step "Setting up SSH tunnel to remote Docker..."
        chmod +x scripts/connect-docker.sh
        
        # Try to establish SSH tunnel
        print_step "Establishing SSH tunnel to Docker daemon..."
        source scripts/connect-docker.sh
        
        if [ $? -eq 0 ]; then
            print_success "SSH tunnel to remote Docker established"
        else
            print_warning "SSH tunnel setup had issues, but continuing..."
        fi
    else
        print_error "SSH tunnel script not found. Please ensure scripts/connect-docker.sh exists"
        exit 1
    fi
else
    print_success "DOCKER_HOST already configured: $DOCKER_HOST"
fi

# Test Docker connection
print_step "Testing Docker connection..."
if docker info &> /dev/null; then
    print_success "Docker connection successful"
    docker info | grep "Server Version" || true
else
    print_error "Cannot connect to Docker daemon. Please check SSH tunnel and remote Docker setup."
    print_error "Current DOCKER_HOST: ${DOCKER_HOST:-'not set'}"
    exit 1
fi

# Check if docker-compose is available
print_step "Checking Docker Compose..."
if ! command -v docker-compose &> /dev/null; then
    if ! docker compose version &> /dev/null; then
        print_error "Docker Compose is not available. Please install Docker Compose."
        exit 1
    else
        DOCKER_COMPOSE_CMD="docker compose"
    fi
else
    DOCKER_COMPOSE_CMD="docker-compose"
fi

print_success "Docker Compose is available ($DOCKER_COMPOSE_CMD)"

# Set up environment file for local development with remote Docker
print_step "Setting up environment configuration..."
if [ ! -f ".env.local" ]; then
    cat > .env.local << 'EOF'
# NetNeural Local Development Environment (Remote Docker)
# Generated by setup script

# Supabase Configuration (Local Development)
NEXT_PUBLIC_SUPABASE_URL=http://localhost:4434
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU

# API Configuration
NEXT_PUBLIC_API_URL=http://localhost:4434

# Authentication
NEXTAUTH_URL=http://localhost:4000
NEXTAUTH_SECRET=super-secret-nextauth-secret-key-for-development

# Database
DATABASE_URL=postgres://postgres:netneural-dev-password@localhost:4432/netneural

# Redis
REDIS_URL=redis://:netneural-redis-password@localhost:4379

# Development Settings
NODE_ENV=development
PORT=3000

# Remote Docker (Auto-configured)
DOCKER_HOST=tcp://localhost:2375
EOF
    print_success "Created .env.local with development configuration"
else
    print_success ".env.local already exists"
fi

# Ensure all necessary directories exist
print_step "Creating necessary directories..."
mkdir -p apps/web/src/components
mkdir -p apps/web/src/pages
mkdir -p apps/web/src/lib
mkdir -p apps/api/src/routes
mkdir -p apps/api/src/middleware
mkdir -p apps/mobile/src/components
mkdir -p packages/types/src
mkdir -p packages/ui/src/components
mkdir -p packages/utils/src
print_success "Project directories created"

# Stop any existing services
print_step "Stopping any existing services..."
$DOCKER_COMPOSE_CMD -f docker/docker-compose.local.yml down --remove-orphans 2>/dev/null || true

# Build Docker images (this will happen on remote Docker)
print_step "Building Docker images on remote server..."
echo "This may take a few minutes as images are built on the remote Docker daemon..."

# Check if we can pull base images first
print_step "Checking remote Docker registry access..."
docker pull node:18-alpine > /dev/null 2>&1 || print_warning "Could not pull base images - will try to build anyway"

# Build and start services
print_step "Starting NetNeural services on remote Docker..."
$DOCKER_COMPOSE_CMD -f docker/docker-compose.local.yml up -d --build

# Wait for services to be ready
print_step "Waiting for services to start..."
sleep 15

# Check service health
print_step "Checking service status..."
$DOCKER_COMPOSE_CMD -f docker/docker-compose.local.yml ps

# Test key service endpoints
print_step "Testing service connectivity..."

# Test database connectivity
max_attempts=30
attempt=0
while [ $attempt -lt $max_attempts ]; do
    if nc -z localhost 4432 2>/dev/null; then
        print_success "Database is responding on port 4432"
        break
    fi
    attempt=$((attempt + 1))
    echo "Waiting for database... ($attempt/$max_attempts)"
    sleep 2
done

# Test Supabase Studio
if curl -f http://localhost:4001 >/dev/null 2>&1; then
    print_success "Supabase Studio is responding"
else
    print_warning "Supabase Studio not responding yet - may need more time"
fi

# Test PostgREST API
if curl -f http://localhost:4434 >/dev/null 2>&1; then
    print_success "PostgREST API is responding"
else
    print_warning "PostgREST API not responding yet - may need more time"
fi

echo ""
echo "🎉 NetNeural Development Environment Setup Complete!"
echo "=================================================="
echo ""
echo "🔗 Remote Docker Configuration:"
echo "   Docker Host: ${DOCKER_HOST:-'localhost'}"
echo "   SSH Tunnel: Active (if configured)"
echo ""
echo "📍 Service URLs (Local Access):"
echo "   🌐 NetNeural Web App:    http://localhost:4000"
echo "   🛠️ Supabase Studio:      http://localhost:4001"
echo "   🔗 REST API (PostgREST): http://localhost:4434"
echo "   🔐 Auth (GoTrue):        http://localhost:4433"
echo "   💾 Storage API:          http://localhost:4436"
echo "   ⚡ Realtime WebSocket:   ws://localhost:4435"
echo "   🗄️ PostgreSQL:           localhost:4432"
echo "   📊 Redis:                localhost:4379"
echo "   🔄 Traefik Dashboard:    http://localhost:4080"
echo ""
echo "🛠️ Development Commands:"
echo "   Start development:      npm run dev"
echo "   View logs:              npm run docker:local:logs"
echo "   Stop services:          npm run docker:local:down"
echo "   Restart services:       docker-compose -f docker/docker-compose.local.yml restart"
echo ""
echo "📱 24-Hour MVP Development:"
echo "   Web app source:         apps/web/src/"
echo "   API source:             apps/api/src/"
echo "   Mobile source:          apps/mobile/src/"
echo "   Shared packages:        packages/"
echo ""
echo "📚 Next Steps for 24-Hour MVP:"
echo "   1. Access Supabase Studio: http://localhost:4001"
echo "   2. Set up database tables for MVP"
echo "   3. Start developing modular components"
echo "   4. Import legacy UI patterns as inspiration"
echo ""
print_success "Ready to start 24-hour MVP development!"
print_warning "Remember: Services are running on remote Docker via SSH tunnel"
