#!/bin/bash

# ============================================================================
# Quick Staging Migration Apply Script
# ============================================================================
# Automatically creates ready-to-paste SQL files for Supabase Dashboard
# ============================================================================

echo "🚀 NetNeural Staging Migration Helper"
echo ""
echo "Available quick-fix migrations:"
echo ""
echo "1. 📊 Telemetry System (FIXES AI ANALYTICS 400 ERROR)"
echo "   File: supabase/migrations/STAGING_TELEMETRY_FIX.sql"
echo "   Creates device_telemetry_history table + RLS policies"
echo ""
echo "2. 🔧 Device Types (FIXES ADD DEVICE DROPDOWN)"
echo "   File: supabase/migrations/20260219000001_device_types.sql"
echo "   Creates device_types table"
echo ""
echo "   File: supabase/migrations/20260220000002_auto_create_device_types.sql"
echo "   Auto-creates 42 standard device types for all orgs"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 How to apply:"
echo ""
echo "1. Go to: https://supabase.com/dashboard"
echo "2. Select staging project: atgbmxicqikmapfqouco"
echo "3. Click: SQL Editor → New Query"
echo "4. Copy contents of migration file (see above)"
echo "5. Paste into SQL Editor"
echo "6. Click: Run"
echo "7. Verify success (should see ✅ message)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Copy a migration file:"
echo ""
echo "   # Telemetry (AI Analytics fix)"
echo "   cat supabase/migrations/STAGING_TELEMETRY_FIX.sql | pbcopy"
echo ""
echo "   # Device Types"
echo "   cat supabase/migrations/20260219000001_device_types.sql | pbcopy"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 Check what's missing (requires service role key):"
echo ""
echo "   export STAGING_SERVICE_ROLE_KEY='your-key-from-dashboard'"
echo "   node scripts/check-staging-migrations.js"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
